# Generated by Django 3.1.1 on 2021-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='body_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='glucode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='oxygen_saturation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='respiration',
            field=models.IntegerField(default=0),
        ),
    ]
