# Generated by Django 3.1.1 on 2021-01-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('body_temp', models.IntegerField(null=True)),
                ('blood_pressure', models.IntegerField(null=True)),
                ('respiration', models.IntegerField(null=True)),
                ('glucode', models.IntegerField(null=True)),
                ('heart_rate', models.IntegerField(null=True)),
                ('oxygen_saturation', models.IntegerField(null=True)),
            ],
        ),
    ]
