# Generated by Django 3.1.1 on 2021-01-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210127_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='glucode',
            new_name='glucose',
        ),
    ]
